services:
  robot-gateway:
    image: ghcr.io/shiwarai/rds-2p-assistants-skills-robot-gateway:main

  salute:
    image: ghcr.io/shiwarai/rds-2p-assistants-skills-salute:main
    build: !override null

  alice:
    image: ghcr.io/shiwarai/rds-2p-assistants-skills-alice:main
    build: !override null
