# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: robot.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'robot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0brobot.proto\x12\x05robot\"\'\n\x13RobotConnectRequest\x12\x10\n\x08robot_id\x18\x01 \x01(\t\"\xbe\x01\n\rStreamMessage\x12\x31\n\x0c\x62inding_code\x18\x01 \x01(\x0b\x32\x19.robot.BindingCodeMessageH\x00\x12!\n\x07\x63ommand\x18\x02 \x01(\x0b\x32\x0e.robot.CommandH\x00\x12$\n\x05\x65rror\x18\x03 \x01(\x0b\x32\x13.robot.ErrorMessageH\x00\x12&\n\x06status\x18\x04 \x01(\x0b\x32\x14.robot.StatusMessageH\x00\x42\t\n\x07message\"6\n\x12\x42indingCodeMessage\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x12\n\nexpires_at\x18\x02 \x01(\x03\"F\n\x07\x43ommand\x12\x14\n\x0c\x63ommand_text\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x12\n\ncommand_id\x18\x03 \x01(\t\"9\n\x0c\x45rrorMessage\x12\x12\n\nerror_code\x18\x01 \x01(\t\x12\x15\n\rerror_message\x18\x02 \x01(\t\"0\n\rStatusMessage\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2[\n\x13RobotCommandService\x12\x44\n\x0eStreamCommands\x12\x1a.robot.RobotConnectRequest\x1a\x14.robot.StreamMessage0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROBOTCONNECTREQUEST']._serialized_start=22
  _globals['_ROBOTCONNECTREQUEST']._serialized_end=61
  _globals['_STREAMMESSAGE']._serialized_start=64
  _globals['_STREAMMESSAGE']._serialized_end=254
  _globals['_BINDINGCODEMESSAGE']._serialized_start=256
  _globals['_BINDINGCODEMESSAGE']._serialized_end=310
  _globals['_COMMAND']._serialized_start=312
  _globals['_COMMAND']._serialized_end=382
  _globals['_ERRORMESSAGE']._serialized_start=384
  _globals['_ERRORMESSAGE']._serialized_end=441
  _globals['_STATUSMESSAGE']._serialized_start=443
  _globals['_STATUSMESSAGE']._serialized_end=491
  _globals['_ROBOTCOMMANDSERVICE']._serialized_start=493
  _globals['_ROBOTCOMMANDSERVICE']._serialized_end=584
# @@protoc_insertion_point(module_scope)
