# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import robot_pb2 as robot__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in robot_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RobotCommandServiceStub(object):
    """Сервис для отправки команд роботам через Server Streaming RPC
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamCommands = channel.unary_stream(
                '/robot.RobotCommandService/StreamCommands',
                request_serializer=robot__pb2.RobotConnectRequest.SerializeToString,
                response_deserializer=robot__pb2.StreamMessage.FromString,
                _registered_method=True)


class RobotCommandServiceServicer(object):
    """Сервис для отправки команд роботам через Server Streaming RPC
    """

    def StreamCommands(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RobotCommandServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamCommands': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamCommands,
                    request_deserializer=robot__pb2.RobotConnectRequest.FromString,
                    response_serializer=robot__pb2.StreamMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'robot.RobotCommandService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('robot.RobotCommandService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RobotCommandService(object):
    """Сервис для отправки команд роботам через Server Streaming RPC
    """

    @staticmethod
    def StreamCommands(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/robot.RobotCommandService/StreamCommands',
            robot__pb2.RobotConnectRequest.SerializeToString,
            robot__pb2.StreamMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
